package EntityResep;
// Generated Nov 14, 2016 1:47:38 AM by Hibernate Tools 4.3.1



/**
 * Resep generated by hbm2java
 */
public class Resep  implements java.io.Serializable {


     private int index;
     private String kdResep;
     private String kdDokter;
     private String kdPasien;
     private String jp;
     private String tglresep;
     private String kdObat;

    public Resep() {
    }

	
    public Resep(int index, String kdResep, String kdDokter, String kdPasien, String jp, String tglresep) {
        this.index = index;
        this.kdResep = kdResep;
        this.kdDokter = kdDokter;
        this.kdPasien = kdPasien;
        this.jp = jp;
        this.tglresep = tglresep;
    }
    public Resep(int index, String kdResep, String kdDokter, String kdPasien, String jp, String tglresep, String kdObat) {
       this.index = index;
       this.kdResep = kdResep;
       this.kdDokter = kdDokter;
       this.kdPasien = kdPasien;
       this.jp = jp;
       this.tglresep = tglresep;
       this.kdObat = kdObat;
    }
   
    public int getIndex() {
        return this.index;
    }
    
    public void setIndex(int index) {
        this.index = index;
    }
    public String getKdResep() {
        return this.kdResep;
    }
    
    public void setKdResep(String kdResep) {
        this.kdResep = kdResep;
    }
    public String getKdDokter() {
        return this.kdDokter;
    }
    
    public void setKdDokter(String kdDokter) {
        this.kdDokter = kdDokter;
    }
    public String getKdPasien() {
        return this.kdPasien;
    }
    
    public void setKdPasien(String kdPasien) {
        this.kdPasien = kdPasien;
    }
    public String getJp() {
        return this.jp;
    }
    
    public void setJp(String jp) {
        this.jp = jp;
    }
    public String getTglresep() {
        return this.tglresep;
    }
    
    public void setTglresep(String tglresep) {
        this.tglresep = tglresep;
    }
    public String getKdObat() {
        return this.kdObat;
    }
    
    public void setKdObat(String kdObat) {
        this.kdObat = kdObat;
    }




}


