/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import EntityDokter.DAODokter;
import EntityDokter.Dokter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.*;


/**
 *
 * @author albi
 */
public class DokterInterface extends javax.swing.JInternalFrame {
    ResultSet rs;
    java.util.List list;
    DefaultTableModel modeldokter;
    /**
     * Creates new form DokterInterface
     */
    public DokterInterface() {
        initComponents();
        modeldokter = (DefaultTableModel) tbldokter.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGJK = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtkddokter = new javax.swing.JTextField();
        txtnmdokter = new javax.swing.JTextField();
        RBl = new javax.swing.JRadioButton();
        RBP = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalt = new javax.swing.JTextArea();
        txtspecial = new javax.swing.JTextField();
        txttlp = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldokter = new javax.swing.JTable();
        btnubah = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(919, 509));

        jLabel1.setText("jLabel1");

        jLabel2.setText("Jenis Kelamin");

        jLabel3.setText("Specialist");

        jLabel4.setText("Alamat");

        jLabel5.setText("Kode Dokter");

        jLabel6.setText("Nama Dokter");

        jLabel7.setText("No telephone");

        jLabel8.setText("Password");

        txtkddokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkddokterActionPerformed(evt);
            }
        });

        BGJK.add(RBl);
        RBl.setText("Laki-Laki");

        BGJK.add(RBP);
        RBP.setText("Perempuan");

        txtalt.setColumns(20);
        txtalt.setRows(5);
        jScrollPane1.setViewportView(txtalt);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        tbldokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Dokter", "Nama Dokter", "Jenis Kelamin", "Specialist", "Alamat", "No Telephone", "Password"
            }
        ));
        tbldokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldokterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldokter);

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnmdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkddokter, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RBl)
                                        .addGap(18, 18, 18)
                                        .addComponent(RBP))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttlp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpass)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtkddokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnmdokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RBl)
                    .addComponent(RBP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btndelete)
                    .addComponent(btnubah)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
       DAODokter daoDokter = new DAODokter();
       Dokter dr = new Dokter();
      try{
    dr.setKdDokter(txtkddokter.getText());
    dr.setNmDokter(txtnmdokter.getText());
     String jekel="";
    if (RBl.isSelected()){
     jekel = "Laki-Laki";
     }
    else{
     jekel = "Perempuan";
         }
    dr.setJeniskelamin(jekel);
    dr.setSpecialist(txtspecial.getText());
    dr.setAlamat(txtalt.getText());
    dr.setTlp(txttlp.getText());
    dr.setPassword(txtpass.getText());
    
    daoDokter.simpanDokter(dr);
    JOptionPane.showMessageDialog (null, "Berhasil Di Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
    bersih();
   
      } 
      catch (Exception E){
       JOptionPane.showMessageDialog (null, "Gagal Di Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
       
      }
       tampiltabel();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
     try{
        DAODokter daoDokter = new DAODokter();
String a = txtkddokter.getText();
  daoDokter.deletDokter(a);
     JOptionPane.showMessageDialog (null, "Berhasil Di Delete", "Title", JOptionPane.INFORMATION_MESSAGE);
     bersih();
     }catch (Exception e){
         JOptionPane.showMessageDialog (null, "Gagal DI Delete", "Title", JOptionPane.INFORMATION_MESSAGE);

     }
     tampiltabel();
    }//GEN-LAST:event_btndeleteActionPerformed

    public  void bersih(){
txtkddokter.setText("");
txtnmdokter.setText("");
RBl.setSelected(true);
txtspecial.setText("");
txtalt.setText("");
txttlp.setText("");
txtpass.setText("");

}
    private void txtkddokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkddokterActionPerformed
DAODokter daoDokter = new DAODokter();
String a = txtkddokter.getText();
try{
  daoDokter.cariDokterByKd(a);
  Dokter dokter = daoDokter.cariDokterByKd(a);
  txtnmdokter.setText(dokter.getNmDokter());
  String jk = dokter.getJeniskelamin();
  if(jk.equals("Laki-Laki")){
      RBl.setSelected(true);
  }
  else{
  RBP.setSelected(true);
   }
  txtspecial.setText(dokter.getSpecialist());
  txtalt.setText(dokter.getAlamat());
  txttlp.setText(dokter.getTlp());
  txtpass.setText(dokter.getPassword());
}
catch (Exception e){
         JOptionPane.showMessageDialog (null, "Kode Dokter Tersebut Tidak Ditemukan", "Title", JOptionPane.INFORMATION_MESSAGE);
         bersih();
     }
      
    }//GEN-LAST:event_txtkddokterActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
       DAODokter daoDokter = new DAODokter();
       Dokter dr = new Dokter();
      try{
    dr.setKdDokter(txtkddokter.getText());
    dr.setNmDokter(txtnmdokter.getText());
     String jekel="";
    if (RBl.isSelected()){
     jekel = "Laki-Laki";
     }
    else{
     jekel = "Perempuan";
         }
    dr.setJeniskelamin(jekel);
    dr.setSpecialist(txtspecial.getText());
    dr.setAlamat(txtalt.getText());
    dr.setTlp(txttlp.getText());
    dr.setPassword(txtpass.getText());
    
    daoDokter.simpanDokter(dr);
    JOptionPane.showMessageDialog (null, "Berhasil Di Ubah", "Title", JOptionPane.INFORMATION_MESSAGE);
   bersih();
      } 
      catch (Exception E){
       JOptionPane.showMessageDialog (null, "Gagal Di Ubah", "Title", JOptionPane.INFORMATION_MESSAGE);
      }
       tampiltabel();
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        bersih();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tbldokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldokterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbldokterMouseClicked

    public  void tampiltabel(){
    DAODokter daoDokter = new DAODokter();
    while(modeldokter.getRowCount()> 0){
    modeldokter.removeRow(0);
    }
    List<Dokter> data = daoDokter.getData();
    Iterator it = data.iterator();
    Dokter dok = null;
        while (it.hasNext()) {
           dok = (Dokter) it.next();
           modeldokter.addRow(new Object[]{dok.getKdDokter(),dok.getNmDokter(),dok.getJeniskelamin(),dok.getSpecialist(),dok.getAlamat(),dok.getTlp(),dok.getPassword()});   
        }
    
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGJK;
    private javax.swing.JRadioButton RBP;
    private javax.swing.JRadioButton RBl;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbldokter;
    private javax.swing.JTextArea txtalt;
    private javax.swing.JTextField txtkddokter;
    private javax.swing.JTextField txtnmdokter;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtspecial;
    private javax.swing.JTextField txttlp;
    // End of variables declaration//GEN-END:variables
}
