/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import EntityResep.DAOResep;
import EntityResep.Resep;
import com.klinik3.util.HibernateUtil;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.*;
import org.hibernate.Session;

/**
 *
 * @author albi
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {
ResultSet rs;
    java.util.List list;
    DefaultTableModel modelresep;
    Session session = null;
    /**
     * Creates new form NewJInternalFrame
     */
    public NewJInternalFrame() {
        initComponents();
        modelresep = (DefaultTableModel) tblresep.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblresep = new javax.swing.JTable();
        txtkdresep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btncari = new javax.swing.JButton();

        tblresep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Resep", "Kode Dokter", "Kode Pasien", "Tanggal Resep", "Kode Obat"
            }
        ));
        jScrollPane1.setViewportView(tblresep);

        jLabel1.setText("Kode Resep");

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(txtkdresep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btncari)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkdresep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
     cariresep();
    }//GEN-LAST:event_btncariActionPerformed

    public void cariresep(){
        String a = txtkdresep.getText();
    
        session = HibernateUtil.getSessionFactory().openSession();
         DAOResep daoResep = new DAOResep ();
    while(modelresep.getRowCount()> 0){
    modelresep.removeRow(0);
    }
 List<Resep> resep1 = session.createQuery("from Resep where kdResep=:kdResep")
                                                        .setString("kdResep", a).list();
        for (Resep resep11 : resep1){

          modelresep.addRow(new Object[]{resep11.getKdResep(),resep11.getKdDokter(),resep11.getKdPasien(),resep11.getTglresep(),resep11.getKdObat()});   
    

    
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblresep;
    private javax.swing.JTextField txtkdresep;
    // End of variables declaration//GEN-END:variables
}
