/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import EntityObat.DAOObat;
import EntityObat.Obat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author albi
 */
public class ObatInterface extends javax.swing.JInternalFrame {
  ResultSet rs;
    java.util.List list;
    DefaultTableModel modelobat;
   
    /**
     * Creates new form ObatInterface
     */
    public ObatInterface() {
        initComponents();
        modelobat = (DefaultTableModel) tblobat.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkdobat = new javax.swing.JTextField();
        txtnmobat = new javax.swing.JTextField();
        cmbjo = new javax.swing.JComboBox();
        txtharga = new javax.swing.JTextField();
        tglkadaluarsa = new com.toedter.calendar.JDateChooser();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblobat = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(919, 509));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Form Obat");

        jLabel2.setText("Kode Obat");

        jLabel3.setText("Nama Obat");

        jLabel4.setText("Jenis Obat");

        jLabel5.setText("Tanggal Kadaluarsa");

        jLabel6.setText("Harga");

        txtkdobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdobatActionPerformed(evt);
            }
        });

        cmbjo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--PILIH--", "kapsul", "tablet", "cair" }));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btndelete.setText("Hapus");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        tblobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Obat", "Nama Obat", "Jenis Obat", "Tanggal Kadaluarsa", "Harga"
            }
        ));
        tblobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblobatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblobat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(tglkadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(81, 81, 81))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6))
                                        .addGap(78, 78, 78)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnmobat, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbjo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkdobat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan)
                                .addGap(28, 28, 28)
                                .addComponent(btnubah)
                                .addGap(18, 18, 18)
                                .addComponent(btndelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnreset)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkdobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnmobat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbjo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(tglkadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan)
                            .addComponent(btnubah)
                            .addComponent(btndelete)
                            .addComponent(btnreset)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
       DAOObat daoObat = new DAOObat();
       Obat ob = new Obat();
        String tampilan ="yyyy-MM-dd" ; 
SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
      try{
    ob.setKdObat(txtkdobat.getText());
    ob.setNmObat(txtnmobat.getText());
    String jekel="";
    int pil1=0;
    String jo="";
            pil1 = cmbjo.getSelectedIndex();
            if (pil1==0) { jo="";}
            if (pil1==1) { jo="kapsul";}
            if (pil1==2) { jo="tablet";}
            if (pil1==3) { jo="cair";}
           String tanggal = String.valueOf(fm.format(tglkadaluarsa.getDate()));
    ob.setJenisobat(jo);
    ob.setTglkadaluarsa(tanggal);
    ob.setHarga(txtharga.getText());
   
    
    daoObat.simpanObat(ob);
    JOptionPane.showMessageDialog (null, "Berhasil Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
    bersih();
      } 
      catch (Exception E){
       JOptionPane.showMessageDialog (null, "Gagal Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
      }
     tampiltabel();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try{
        DAOObat daoObat = new DAOObat();
String a = txtkdobat.getText();
  daoObat.deletObat(a);
     JOptionPane.showMessageDialog (null, "Berhasil Di Delete", "Title", JOptionPane.INFORMATION_MESSAGE);
      bersih();
     }catch (Exception e){
         JOptionPane.showMessageDialog (null, "Gagal DI Delete", "Title", JOptionPane.INFORMATION_MESSAGE);
     }
        tampiltabel();
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtkdobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdobatActionPerformed
       DAOObat daoObat = new DAOObat();
String a = txtkdobat.getText();
try{
  daoObat.cariObatByKd(a);
  Obat obat = daoObat.cariObatByKd(a);
  txtnmobat.setText(obat.getNmObat());
  String jo = obat.getJenisobat();
   if(jo.equals("kapsul")){
     cmbjo.setSelectedIndex(1);
     }
     if(jo.equals("tablet")){
     cmbjo.setSelectedIndex(2);
     }
     if(jo.equals("cair")){
     cmbjo.setSelectedIndex(3);
     }
    String dateValue = obat.getTglkadaluarsa();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
Date tgl = sdf.parse(dateValue);
tglkadaluarsa.setDate(tgl);
txtharga.setText(obat.getHarga());
}catch (Exception E){}
    }//GEN-LAST:event_txtkdobatActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        bersih();
    }//GEN-LAST:event_btnresetActionPerformed

    private void tblobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblobatMouseClicked
     try{
        txtkdobat.setText(String.valueOf(tblobat.getValueAt(tblobat.getSelectedRow(), 0)));
     txtnmobat.setText(String.valueOf(tblobat.getValueAt(tblobat.getSelectedRow(), 1)));
     String jo = String.valueOf(tblobat.getValueAt(tblobat.getSelectedRow(), 2));
     if(jo.equals("kapsul")){
     cmbjo.setSelectedIndex(1);
     }
     if(jo.equals("tablet")){
     cmbjo.setSelectedIndex(2);
     }
     if(jo.equals("cair")){
     cmbjo.setSelectedIndex(3);
     }
      String dateValue = String.valueOf(tblobat.getValueAt(tblobat.getSelectedRow(), 3));
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
Date tgl = sdf.parse(dateValue);
tglkadaluarsa.setDate(tgl);
txtharga.setText(String.valueOf(tblobat.getValueAt(tblobat.getSelectedRow(), 4)));
} catch (Exception e){

}


    }//GEN-LAST:event_tblobatMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
          DAOObat daoObat = new DAOObat();
       Obat ob = new Obat();
        String tampilan ="yyyy-MM-dd" ; 
SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
      try{
    ob.setKdObat(txtkdobat.getText());
    ob.setNmObat(txtnmobat.getText());
    String jekel="";
    int pil1=0;
    String jo="";
            pil1 = cmbjo.getSelectedIndex();
            if (pil1==0) { jo="";}
            if (pil1==1) { jo="kapsul";}
            if (pil1==2) { jo="tablet";}
            if (pil1==3) { jo="cair";}
           String tanggal = String.valueOf(fm.format(tglkadaluarsa.getDate()));
    ob.setJenisobat(jo);
    ob.setTglkadaluarsa(tanggal);
    ob.setHarga(txtharga.getText());
   
    
    daoObat.simpanObat(ob);
    JOptionPane.showMessageDialog (null, "Berhasil Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
    bersih();
      } 
      catch (Exception E){
       JOptionPane.showMessageDialog (null, "Gagal Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
      }
     tampiltabel();
    }//GEN-LAST:event_btnubahActionPerformed

    public void bersih(){
    txtkdobat.setText("");
    txtnmobat.setText("");
    cmbjo.setSelectedIndex(0);
    tglkadaluarsa.setCalendar(null);
    txtharga.setText("");
    }
      public  void tampiltabel(){
   DAOObat daoObat = new DAOObat();
    while(modelobat.getRowCount()> 0){
    modelobat.removeRow(0);
    }
    List<Obat> data = daoObat.getData();
    Iterator it = data.iterator();
    Obat obat = null;
        while (it.hasNext()) {
           obat = (Obat) it.next();
          modelobat.addRow(new Object[]{obat.getKdObat(),obat.getNmObat(),obat.getJenisobat(),obat.getTglkadaluarsa(),obat.getHarga()});   
        }
    
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox cmbjo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblobat;
    private com.toedter.calendar.JDateChooser tglkadaluarsa;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkdobat;
    private javax.swing.JTextField txtnmobat;
    // End of variables declaration//GEN-END:variables
}
