/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import EntityPasien.DAOPasien;
import EntityPasien.Pasien;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Iterator;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
/**
 *
 * @author albi
 */
public class PasienInterface extends javax.swing.JInternalFrame {
ResultSet rs;
    java.util.List list;
    DefaultTableModel modelpasien;
    /**
     * Creates new form PasienInterface
     */
    public PasienInterface() {
        initComponents();
        modelpasien = (DefaultTableModel) tblpasien.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RGJK = new javax.swing.ButtonGroup();
        btnsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtkdpasien = new javax.swing.JTextField();
        txtnmpasien = new javax.swing.JTextField();
        RBl = new javax.swing.JRadioButton();
        RBP = new javax.swing.JRadioButton();
        txtumr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalt = new javax.swing.JTextArea();
        txttlp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        btnubah = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(919, 509));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("Kode Pasien");

        jLabel3.setText("Nama Pasien");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Umur");

        jLabel6.setText("Alamat");

        jLabel7.setText("No telepon");

        txtkdpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdpasienActionPerformed(evt);
            }
        });

        RGJK.add(RBl);
        RBl.setText("Laki-Laki");

        RGJK.add(RBP);
        RBP.setText("Perempuan");

        txtalt.setColumns(20);
        txtalt.setRows(5);
        jScrollPane1.setViewportView(txtalt);

        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pasien", "Nama Pasien", "Jenis Kelamin", "Umur", "Alamat", "No telepon"
            }
        ));
        tblpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpasien);

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btndelete.setText("Hapus");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkdpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnmpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttlp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RBl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtumr))
                                .addGap(18, 18, 18)
                                .addComponent(RBP))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnubah)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete)
                        .addGap(28, 28, 28)
                        .addComponent(btnreset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtkdpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnmpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(RBl)
                            .addComponent(RBP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtumr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txttlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan)
                            .addComponent(btnubah)
                            .addComponent(btndelete)
                            .addComponent(btnreset))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
      DAOPasien daoPasien = new DAOPasien();
       Pasien p = new Pasien();
      try{
  p.setKdPasien(txtkdpasien.getText());
  p.setNmPasien(txtnmpasien.getText());
    String jekel="";
    if (RBl.isSelected()){
     jekel = "Laki-Laki";
     }
    else{
     jekel = "Perempuan";
         }
   p.setJeniskelamin(jekel);
   p.setUp(txtumr.getText());
   p.setAlamat(txtalt.getText());
   p.setTlp(txttlp.getText());
    
    daoPasien.simpanPasien(p);
    JOptionPane.showMessageDialog (null, "Berhasil Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
bersih();
      } 
      catch (Exception E){
       JOptionPane.showMessageDialog (null, "Gagal Menyimpan", "Title", JOptionPane.INFORMATION_MESSAGE);
      }
      tampiltabel();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
         DAOPasien daoPasien = new DAOPasien();
       Pasien p = new Pasien();
      try{
  p.setKdPasien(txtkdpasien.getText());
  p.setNmPasien(txtnmpasien.getText());
    String jekel="";
    if (RBl.isSelected()){
     jekel = "Laki-Laki";
     }
    else{
     jekel = "Perempuan";
         }
   p.setJeniskelamin(jekel);
   p.setUp(txtumr.getText());
   p.setAlamat(txtalt.getText());
   p.setTlp(txttlp.getText());
    
    daoPasien.simpanPasien(p);
    JOptionPane.showMessageDialog (null, "Berhasil Di Ubah", "Title", JOptionPane.INFORMATION_MESSAGE);
    bersih();
      } 
      catch (Exception E){
       JOptionPane.showMessageDialog (null, "Gagal Di Ubah", "Title", JOptionPane.INFORMATION_MESSAGE);
      }
      tampiltabel();
    }//GEN-LAST:event_btnubahActionPerformed

    private void txtkdpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdpasienActionPerformed
   DAOPasien daoPasien = new DAOPasien();
String a = txtkdpasien.getText();
try{
  daoPasien.cariPasienByKd(a);
  Pasien pasien = daoPasien.cariPasienByKd(a);
  txtnmpasien.setText(pasien.getNmPasien());
  String jk = pasien.getJeniskelamin();
  if(jk.equals("Laki-Laki")){
      RBl.setSelected(true);
  }
  else{
  RBP.setSelected(true);
   }
  txtumr.setText(pasien.getUp());
  txtalt.setText(pasien.getAlamat());
  txttlp.setText(pasien.getTlp());
}catch(Exception e){
JOptionPane.showMessageDialog (null, "Kode Dokter Tersebut Tidak Ditemukan", "Title", JOptionPane.INFORMATION_MESSAGE);
         bersih();
}
    }//GEN-LAST:event_txtkdpasienActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
      bersih();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       try{
         DAOPasien daoPasien = new DAOPasien();
String a = txtkdpasien.getText();
  daoPasien.deletPasien(a);
     JOptionPane.showMessageDialog (null, "Berhasil Di Delete", "Title", JOptionPane.INFORMATION_MESSAGE);
      bersih();
     }catch (Exception e){
         JOptionPane.showMessageDialog (null, "Gagal DI Delete", "Title", JOptionPane.INFORMATION_MESSAGE);
     }
        tampiltabel();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpasienMouseClicked
      try{
        txtkdpasien.setText(String.valueOf(tblpasien.getValueAt(tblpasien.getSelectedRow(), 0)));
  txtnmpasien.setText(String.valueOf(tblpasien.getValueAt(tblpasien.getSelectedRow(), 1)));
  String jk = String.valueOf(tblpasien.getValueAt(tblpasien.getSelectedRow(), 2));
  if(jk.equals("Laki-Laki")){
      RBl.setSelected(true);
  }
  else{
  RBP.setSelected(true);
   }
  txtumr.setText(String.valueOf(tblpasien.getValueAt(tblpasien.getSelectedRow(), 3)));
  txtalt.setText(String.valueOf(tblpasien.getValueAt(tblpasien.getSelectedRow(), 4)));
  txttlp.setText(String.valueOf(tblpasien.getValueAt(tblpasien.getSelectedRow(), 5)));
  
} catch (Exception e){

}
    }//GEN-LAST:event_tblpasienMouseClicked

    public void bersih(){
    txtkdpasien.setText("");
    txtnmpasien.setText("");
    RBl.setSelected(true);
    txtumr.setText("");
    txtalt.setText("");
    txttlp.setText("");
    }
    
    public  void tampiltabel(){
    DAOPasien daoPasien = new DAOPasien();
    while(modelpasien.getRowCount()> 0){
    modelpasien.removeRow(0);
    }
    List<Pasien> data = daoPasien.getData();
    Iterator it = data.iterator();
   Pasien pasien = null;
        while (it.hasNext()) {
           pasien = (Pasien) it.next();
          modelpasien.addRow(new Object[]{pasien.getKdPasien(),pasien.getNmPasien(),pasien.getJeniskelamin(),pasien.getUp(),pasien.getAlamat(),pasien.getTlp()});   
        }
    
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBP;
    private javax.swing.JRadioButton RBl;
    private javax.swing.ButtonGroup RGJK;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblpasien;
    private javax.swing.JTextArea txtalt;
    private javax.swing.JTextField txtkdpasien;
    private javax.swing.JTextField txtnmpasien;
    private javax.swing.JTextField txttlp;
    private javax.swing.JTextField txtumr;
    // End of variables declaration//GEN-END:variables
}
